from django.urls import path
from . import views
#create list
urlpatterns=[
  path('',views.index,name='index'),
  path('about/',views.about,name='about'),
  path('contact/',views.contact,name='contact'),
  path('login/',views.login,name='login'),
  path('logcode/',views.logcode,name='logcode'),
  path('adminlayout/',views.adminlayout,name='adminlayout'), 
  path('showenquiry/',views.showenq,name='showenquiry'),
  path('addsession/',views.addsession,name="addsession"),
  path('assave/',views.assave,name='assave'),
  path('addcourse/',views.addcourse,name='addcourse'),
  path('viewcou/',views.viewcou,name='viewcou'),
  path('deletesession/<int:id>',views.deletesession,name='deletesession'),
  path('editsession/<int:id>',views.editsession,name='editsession'),
  # path('updatedata/<int:id>',views.updatedata,name="updatedata"),
  path('deleteenq/<int:id>',views.deleteenq,name='deleteenq'),
  path('deletecou/<int:id>',views.deletecou,name='deletecou'),
  path('addstudent/',views.addstudent,name='addstudent'),
  path('studentdash/',views.studentdash,name='studentdash'),
  path('applicationform/',views.applicationform,name='applicationform'),
  path('saveinfo/',views.saveinfo,name='saveinfo'),
  path('location/',views.location,name='location'),
  path('parkluck/',views.parkluck,name='parkluck'),
  path('Certification/',views.Certification,name='Certification'),
  path('viewses/',views.viewses,name='viewses'),
  path('uploaddoc/',views.uploaddoc,name='uploaddoc'),
  path('verifydoc/',views.verifydoc,name='verifydoc'),
  path('collaborators/',views.collaborators,name='collaborators'),
  path('knowldge/',views.knowldge,name='knowldge'),
  path('ceo/',views.ceo,name='ceo'),
  path('distinguished/',views.distinguished,name='distinguished'),
  path('scientific/',views.scientific,name='scientific'),
  path('verifystu/<int:id>',views.verifystu,name='verifystu'),
  path('payfees/',views.payfees,name='payfees'),
  path('finalsubmit/',views.finalsubmit,name='finalsubmit'),
  path('finalverification/',views.finalverification,name='finalverification'),
  path('assign/<int:id>',views.assign,name='assign'),
  path('finalstudents/',views.finalstudents,name='finalstudents'),
  path('viewstudent/',views.viewstudent,name='viewstudent'),
  path('logout/',views.logout,name='logout'),
  path('changepass/',views.changepass,name='changepass'),
  path('changesave/',views.changesave,name='changesave'),
  path('admindash/',views.admindash,name='admindash'),
]

#adminlayout   