# Generated by Django 5.1 on 2024-09-13 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oasapp', '0003_session'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='session',
            new_name='tbl_session',
        ),
    ]
